site_name: Million Tile Engine (MTE)
theme: material

extra:
  palette:
    primary: 'lime'
    accent: 'amber'

# Set this to true to host the build with a web server.
# use_directory_urls: false


pages:
- General: 'index.md'
- API: 'api.md'
- Reserved Tile Properties: 'reserved-tile-props.md'
- Sprite Properties: 'sprite-props.md'
- Tile Properties: 'tile-props.md'